### ISSUE TITLE
Help me compile

### ISSUE THREAD

**Issue by ahonxxx** [mercenaruss/uzg-firmware#1]
How to solve this, thanks
![2](https://github.com/mercenaruss/uzg-firmware/assets/54906315/8bd9f0b1-a7d4-4a97-a739-33ae6eb46b6a)

**Comment by mercenaruss** [comment]
@ahonxxx create a new folder: webh , inside src folder.
after:

Go to the folder tools/webfilesbuilder;
Run: npm install
Run: npx gulp

Then you will be able to build.

**Comment by ahonxxx** [comment]
> @ahonxxx create a new folder: webh , inside src folder. after:
> 
> Go to the folder tools/webfilesbuilder; Run: npm install Run: npx gulp
> 
> Then you will be able to build.

Do you need to modify package.json   There are no files under webh

**Comment by mercenaruss** [comment]
> 

no,just follow instruction above.

**Comment by xyzroe** [comment]
> Still the same. There's nothing in the webh folder ![123123](https://user-images.githubusercontent.com/54906315/263918815-e4ee5c5b-0c1b-4534-b407-53309adae8bf.png)

That's because you didn't run npx gulp command
