### ISSUE TITLE
Config MQTT (auto discovery)

### ISSUE THREAD

**Issue by Razzer90** [mercenaruss/uzg-firmware#14]
hi, thanks for the great update. i'm just a bit at a loss as to how i can display the mqtt as sensors in home assistant? or restart the gateway via mqtt? i can see the individual mqtt states from the uzg in the mqtt explorer. but unfortunately there is no auto discovery in home assistant. thanks again!

**Comment by xyzroe** [comment]
Did you enable toggle that called "Discovery" ?

**Comment by Razzer90** [comment]
yes the switch is on, i also see everything in mqtt explorer, but mqtt has no entries from the uzg

**Comment by xyzroe** [comment]
Just checked myself
<img width="1355" alt="Screenshot 2024-01-13 at 11 51 16 PM" src="https://github.com/mercenaruss/uzg-firmware/assets/6440415/b0c15f58-7622-433e-af42-a0b80152ef62">
<img width="1372" alt="Screenshot 2024-01-13 at 11 51 05 PM" src="https://github.com/mercenaruss/uzg-firmware/assets/6440415/895e4701-28a7-48ea-b80e-423f628edfa0">
<img width="1128" alt="Screenshot 2024-01-13 at 11 50 53 PM" src="https://github.com/mercenaruss/uzg-firmware/assets/6440415/a3f23f73-2b69-4d7c-8202-15c41a8b831f">

**Comment by Razzer90** [comment]
thanks for your help! i tried everything, home assistant reboot, uzg reflashed etc. the solution for me, i renamed the mqtt topic and it came up! perfect!

**Comment by xyzroe** [comment]
What name topic had before rename and after?

**Comment by Razzer90** [comment]
it was previously called Zigstar UZG-01, which did not work.
now simply UZG-01 and it worked immediately

**Comment by xyzroe** [comment]
So it was a space in the topic name?

**Comment by Razzer90** [comment]
yes, there was a space in between

**Comment by xyzroe** [comment]
Add check input mqtt topic

**Comment by dilighiani** [comment]
Can I run 2 instances of HomeAssistant (on 2 separate machines), one connects via ZHA and the other connects to the MQTT broker available on the UZG?

I tried first with ZHA, but then I am not able to make it to connect to the MQTT broker (enabled on the UZG).

**Comment by dilighiani** [comment]
> connecting to the ZHA brings up Zigbee functionality but MQTT brings only internal states of your ZigStar. so the main purpose is different. what do you try to make?

Yes, now I re-read your words and I understand that the MQTT page brings ONLY the internal states of the device.
