### ISSUE TITLE
Change priority for Device Operating Mode

### ISSUE THREAD

**Issue by dilighiani** [mercenaruss/uzg-firmware#16]
Hi,
As I am trying to find the best position in the house I am switching from Ethernet to Wifi and I have problems reconnecting to the device if I do not specify before the interface that will be used.
I suggest a feature request to permit defining the order (Ethernet, Wifi) and have a setting to always prefer Ethernet whenever is connected.

Thank you!

**Comment by habitats-tech** [comment]
I second this request.

**Comment by mercenaruss** [comment]
This will be done in new firmware.
