### ISSUE TITLE
need explanation on the PubSubClient/MQTT code

### ISSUE THREAD

**Issue by michcfr** [mercenaruss/uzg-firmware#18]
Hello,
I am trying to understand the source ugz-firmware:
I have noticed some MQTT related code using the PubSubClient lib. But I thought that the MQTT part is managed by the Zigbee2MQTT code at the server side.
What is the purpose of this code? just checking the connection with the MQTT server?

Regards

**Comment by xyzroe** [comment]
Is's not an issue at all, by the way :)
