### ISSUE TITLE
Can't OTA ESP32 Firmware

### ISSUE THREAD

**Issue by BWilky** [mercenaruss/uzg-firmware#19]
Can't for the life of me get the firmware to upgrade from v.0.1.5 OTA. It goes through the whole process then reboots and firmware reports same. Any tricks? Is there an issue with this version?

**Comment by xyzroe** [comment]
Some network errors. You could try to move close, use another network, or use USB

**Comment by xyzroe** [comment]
You should try to install manually using web installer on zig-star.com v0.2.5 and setup time zone. I think it will allow to make next updates using OTA, with no problems.

**Comment by BWilky** [comment]
The fix was being local on the same network vs vpn. Bryce Sent from my iPhoneOn Mar 21, 2024, at 12:49 PM, xyzroe ***@***.***> wrote:﻿
You should try to install manually using web installer on zig-star.com v0.2.5 and setup time zone. I think it will allow to make next updates using OTA, with no problems.
