### ISSUE TITLE
Bug web.cpp? 

### ISSUE THREAD

**Issue by radioelf** [mercenaruss/uzg-firmware#23]
Hi.
I think there is an error in lines 120, 122, 124, 126, 128, 130, 132, 134, and 136 of the file web.cpp, they all contain the same code. "{ sendGzip(contTypeTextHtml, PAGE_LOADER_html_gz, PAGE_LOADER_html_gz_len); });"

**Comment by xyzroe** [comment]
but on different endpoints

**Comment by radioelf** [comment]
Sorry, I thought the correct way was, for example, "serverWeb.on("/security", { sendGzip(contTypeTextHtml, PAGE_SECURITY_html_gz, PAGE_SECURITY_html_gz_len); });"
