### ISSUE TITLE
upgrade firmware 0.2.0 -> 0.2.3 not working

### ISSUE THREAD

**Issue by saintfrater** [mercenaruss/uzg-firmware#25]
Hello,

The web interface notify  about new ESP32 update available (v0.2.3).

I've tryed to upgrade via **System and Tools** -> **Firmware Upgrade** -> **Install later from github** 

the text change to *Github download starting...* but nothing change... 

I've also tryed via the manual procedure *"choose file..."* and click to *"ESP32 file update"* without other success.

here is the hardware/software information:

**Zig-Star model:**  UZG-01
**ESP32 fw ver:** 0.2.0 (prod-solo)
**ESP32 hw version:** ESP32-D0WDQ6
**CC2652P hw version:** CC2652PXX
**CC2652P fw rev:** 20230507

the UZG is connected via ethernet (static IP)

browser's console:
```
18:30:13,931 Cette page est en mode de compatibilité (quirks). La mise en page peut en être affectée. Pour le mode standard, utilisez « <!DOCTYPE html> ». 172.16.0.8

18:30:13,986 La feuille de style http://172.16.0.8/css/required.css a été chargée comme CSS même si son type MIME, « text/javascript », n’est pas « text/css ». 172.16.0.8

18:30:14,243 [loadPage] url: / functions.js:204:10

18:30:15,560 [apiGetPage] starting parse values functions.js:369:12

18:30:16,809 [modalConstructor] start functions.js:597:10

18:30:16,812 New firmware (v0.2.3) was found on GitHub. It was downloaded 64 times. Go -> System and Tools -> Firmware update page to get more info. functions.js:1156:13

18:30:20,050 [loadPage] url: /sys-tools functions.js:204:10

18:30:20,152 L’utilisation d’XMLHttpRequest de façon synchrone sur le fil d’exécution principal est obsolète à cause de son impact négatif sur la navigation de l’utilisateur final. Consulter https://xhr.spec.whatwg.org/#sync-warning pour plus d’informations. jquery-min.js:2:79717

18:30:20,174 [apiGetPage] starting parse values functions.js:369:12

18:30:23,884 Propriété « -moz-box-shadow » inconnue.  Déclaration abandonnée. required.css:85:19

18:30:23,884 Jeu de règles ignoré suite à un mauvais sélecteur. required.css:216:9

18:30:23,884 Erreur d’analyse de la valeur pour « -webkit-text-size-adjust ».  Déclaration abandonnée. required.css:319:29

18:30:23,885 Pseudo-classe ou pseudo-élément « -moz-focus-outer » inconnu.  Jeu de règles ignoré suite à un mauvais sélecteur. required.css:2544:13

18:30:23,885 Jeu de règles ignoré suite à un mauvais sélecteur. required.css:2562:35

18:30:31,799 Update from Git started... Just be patient! sys-tools line 2 > injectedScript:110:17

18:30:31,799 Events try functions.js:479:10

18:30:32,314 [flash] start functions.js:472:11
```

I've left the page "active" for 3 hours, and it did not log anything else.

**Comment by xyzroe** [comment]
Could you open Developer tools in your browser and then open Console. After that try to update firmware and note any messages in console. And attach them to your message.

**Comment by saintfrater** [comment]
console log added to first comment.

**Comment by xyzroe** [comment]
I don't see any errors. Possible causes: error in NTP time set from pool.ntp.org, inaccessible GitHub from ESP32.
I just checked update from 0.2.0 to 0.2.3 from GitHub all works perfect. [Video](https://vimeo.com/924653411?share=copy)

Something with your network. 
Also you could try to update manually using https://uzg.zig-star.com/webinstall/ and type C cable.

**Comment by saintfrater** [comment]
indeed, I didn't see any request on my DNS servers....
Since I'm in "static IP", I did not find any way to setup the DNS servers, I think that the setting is missing on static IP setup, and so the UZG is unable to resolve any domains...

**Comment by xyzroe** [comment]
Another possible problem is your timezone is very differs from mine, that could make problems with https. 
In v0.2.4 I added time zone selection.

**Comment by saintfrater** [comment]
I confirm the upgrade works perfectly in DHCP mode... I'll open new "issue/request" for adding DNS setting when using "static IP" setting on ethernet.
