### ISSUE TITLE
Help links start **docs**! and then add them to device web ui 

### ISSUE THREAD

**Issue by electronicm** [mercenaruss/uzg-firmware#26]
Direct links to the relevant help pages would be great.

**Comment by xyzroe** [comment]
Please provide example what do you mean

**Comment by electronicm** [comment]
For example:
"System and Tools" > "Firmware update" link to https://uzg.zig-star.com/flashing-and-updating/
or 
"MQTT" link to the docu from https://github.com/mercenaruss/uzg-manual/issues/1

This way you could create good documentation and the web interface code would stay as small as possible.

**Comment by xyzroe** [comment]
Great idea. You're welcome to contribute either documentation or code. And we will add it. Indeed, help with documentation would be very helpful.
