### ISSUE TITLE
Thread support for CC2652P7

### ISSUE THREAD

**Issue by q20** [mercenaruss/uzg-firmware#27]
Hey there

Any chance you could consider adding Thread support to your firmware?
The TI CC2652P7 supports:
` Bluetooth 5.2 Low Energy, Matter, Thread, Zigbee 3.0 `

It would be great to have another protocol enabled in Home Assistant by the UZG-01.  👍

**Comment by xyzroe** [comment]
Hi.
It can be realized by changing CC2652 firmware, not ESP32. UZG-01 supports any protocol that is supported by CC2652.

**Comment by q20** [comment]
> Hi. It can be realized by changing CC2652 firmware, not ESP32. UZG-01 supports any protocol that is supported by CC2652.

Is the functionality exposed by your firmware, though? Can Home Assistant use the Thread protocol with the device set up as per the instructions uzg.zig-star.com?

**Comment by xyzroe** [comment]
I'm not very familiar with the Thread. But ESP32 receives bytes from cc2652 and transfers them to the socket connection, the same thing works in the other direction.  and it doesn’t matter which protocol runs on these bytes.

**Comment by q20** [comment]
I think I understand: the firmware exposes everything from the TI chip. I guess I should check in at the maintainer of the Koenkk firmware...

**Comment by xyzroe** [comment]
yeah you're absolutely right
