### ISSUE TITLE
Support for install codes

### ISSUE THREAD

**Issue by stemer77** [mercenaruss/uzg-firmware#28]
Does ZigStar UZG-01 supports install codes?
I'm trying to pair Bosch Smoke Detector to my network (https://www.zigbee2mqtt.io/devices/BSD-2.html) and nothing happens. On previous bridge Sonoff ZBDongle-E (ezsp) it pairs without any problems.

**Comment by xyzroe** [comment]
All Zigbee functionality is realized in Zigbee chip (CC2652P7) with its own firmware.
Similar question https://github.com/mercenaruss/uzg-firmware/issues/27 where you can find more details.
