### ISSUE TITLE
Add ability to reset network configuration using button

### ISSUE THREAD

**Issue by quaint-engineer** [mercenaruss/uzg-firmware#30]
It would a nice feature to reset all the network configuration using the rear button on the device.

I ran into an issue where I could not access the WebUI because I forgot to enter my subnet mask for a static IP. I attempted a factory reset but that didn't seem to reset the network section either.

I ended up attaching the gateway directly to my laptop via ethernet and assigning it an IP under the same subnet mask as the default value.

**Comment by xyzroe** [comment]
But it should been already realized. 
Did you try long press (>10s) and didn't get succeed?

**Comment by mercenaruss** [comment]
@xyzroe need to add by default 255.255.255.0 mask,many people forget to set this with static ip config,they assume is already there - because of grey color mask.

**Comment by xyzroe** [comment]
@mercenaruss ok, but your comment is more related to #32

**Comment by mercenaruss** [comment]
Assume this closed.
