### ISSUE TITLE
better support for leds on v1 (CC2652P2)

### ISSUE THREAD

**Issue by 532910** [mercenaruss/uzg-firmware#35]
BLUE / RED / YELLOW buttons are shown for v1, though they don't change anything

![image](https://github.com/mercenaruss/uzg-firmware/assets/14617699/3765f143-482b-41ef-b7c7-4fc8245260a1)

**Comment by xyzroe** [comment]
FW version?

**Comment by 532910** [comment]
the latest one, of course:
ESP32 fw ver: 	0.2.6 (prod-solo)
ESP32 hw version: 	ESP32-D0WDQ6
CC2652P hw version: 	CC2652P2
CC2652P fw rev: 	20230507

**Comment by xyzroe** [comment]
Could you show your board? Because we made tests and all works as expected. Only one idea that I have is your hardware have some differences with that one that I have.

**Comment by 532910** [comment]
Sure, I will show it!
I bought it on Ali, exactly this one: https://aliexpress.com/item/1005004862412451.html?sku_id=12000032544271339

**Comment by xyzroe** [comment]
Please provide original aliexpress.com link , or exactly attach your photos

**Comment by 532910** [comment]
I will attach photos. It's a remote location, so I'll take them next week.

**Comment by xyzroe** [comment]
You are using HamGeek that is not original UZG. Maybe there are some differences from UZG schematics.

**Comment by 532910** [comment]
![front](https://github.com/mercenaruss/uzg-firmware/assets/14617699/39efed8a-7a52-4cef-bcb3-0232c6678898)
![back](https://github.com/mercenaruss/uzg-firmware/assets/14617699/4b7d4717-3148-44e7-9a69-8c570d0719e4)

**Comment by mercenaruss** [comment]
This is not a ZigStar Device. Hamgeek maybe

**Comment by 532910** [comment]
It is hamgeek. No plan to support it?

**Comment by mercenaruss** [comment]
No,sorry.

**Comment by xyzroe** [comment]
there is only a Zigbee LED in your photos. So there is nothing to work from buttons in the UI.

**Comment by 532910** [comment]
I meant, is it possible to detect board modification from the software and hide buttons in the UI?
