### ISSUE TITLE
Status - socket connections

### ISSUE THREAD

**Issue by stormshaker** [mercenaruss/uzg-firmware#38]
Minor error I noticed when reviewing the code; I think the below line should check for == 1, not > 1

https://github.com/mercenaruss/uzg-firmware/blob/813589ad587cbe860589a4334f002e7351525ed1/src/web.cpp#L1343

I have one socket connection, it's displayed as 'Yes, 1 connections' on the status page. This change should fix this to display 'Yes, 1 connection' instead.

**Comment by mercenaruss** [comment]
@xyzroe take this in consideration for new firmware please.
