### ISSUE TITLE
Socket client disconnects, requires ESP32 Restart

### ISSUE THREAD

**Issue by stormshaker** [mercenaruss/uzg-firmware#39]
My ZHA client disconnects from the UZG-01 about every two days and cannot reconnect when it retries. To fix it, I need to use the 'ESP32 Restart' button on the System Tools page of the UZG-01, and then reload ZHA.

<img width="1391" alt="Screenshot 2024-05-14 at 10 55 21 AM" src="https://github.com/mercenaruss/uzg-firmware/assets/2807460/6f186ddb-7b64-436a-a1c4-8861705162ea">
The Raw Data log looks strange when the UZG-01 is in this state:
<img width="806" alt="Screenshot 2024-05-14 at 10 56 41 AM" src="https://github.com/mercenaruss/uzg-firmware/assets/2807460/40d74a26-98d8-4d90-b877-5c91df335c9b">

<img width="392" alt="Screenshot 2024-05-14 at 10 55 38 AM" src="https://github.com/mercenaruss/uzg-firmware/assets/2807460/0e4e3d8c-7a68-47ed-a33c-2f5ea13166c3">

The next time this happens, what logs can I collect to help troubleshoot this issue?

**Comment by itn3rd77** [comment]
Same problem on my side. Console full of hex 'ef' messages. A Zigbee Restart command ist required for client (Home Assistant) to reconnect.

**Comment by BWilky** [comment]
Having this same issue as well. Disconnects constantly.

**Comment by xyzroe** [comment]
@mercenaruss I think it caused by Zigbee chip. What do you think?

**Comment by mercenaruss** [comment]
If you are using version with P7 chip inside,please update the firmware to latest one.
https://github.com/Koenkk/Z-Stack-firmware/discussions/496

Please be sure you choose correct firmware for your chip, and your chip is P7.
