### ISSUE TITLE
Flash ESP32 using esptool.py --port rfc2217://

### ISSUE THREAD

**Issue by joe2xyz** [mercenaruss/uzg-firmware#40]
Hi everybody,

I know I can use esptool.py to flash ESP32 when connected over USB:

```
python3 ./tools/esptool.py --port /dev/ttyUSB0 --baud 460800 write_flash --verify -z --flash_mode dio --flash_freq 40m --flash_size detect 0x0 UZG-01_v*.full.bin
```

And I also found on: https://docs.espressif.com/projects/esptool/en/latest/esp32/esptool/remote-serial-ports.html

that it might be possible to use `--port rfc2217://ADDRESS_OF_SERVER:PORT` for flashing.

so I tried:

```
python3 ./tools/esptool.py --port rfc2217://<IP>:6638 flash_id
```

but that didn't work... Is that possible?

P.S. I know I can use a web updater and I can do it via web management but I'm curious if this can be done via CLI.

Thank you.

**Comment by xyzroe** [comment]
No, it is not possible. 
Only local file upload or github file download update using web UI of gateway.
