### ISSUE TITLE
Unable to update firmware

### ISSUE THREAD

**Issue by jamiebegin** [mercenaruss/uzg-firmware#42]
When I log into the web interface, I get a notification to upgrade to 1.0. However, I am unable to do so. Trying to upgrade directly from Github doesn't do anything. So I then downloaded the release and attempted to upload it via the web interface. However, when I select the file in the file dialog, it is input as "C:\fakepath\XZG_20240526.1.full.bin". So not surprisingly, it doesn't upload correctly there either.

**Comment by xyzroe** [comment]
You could try to restart ESP32 and right after that click install from GitHub, it should help.

To use local file update you need to select https://github.com/mercenaruss/uzg-firmware/releases/download/v1.0.0/UZG-01.bin or https://github.com/xyzroe/XZG/releases/download/20240526.1/XZG_20240526.1.ota.bin
Not *.full.bin but *.ota.bin

**Comment by jamiebegin** [comment]
Not sure why this was marked closed? The suggestion did not work. What ended up working was changing the timezone to UTC.

**Comment by xyzroe** [comment]
What is your local time zone?

**Comment by JohnMcLear** [comment]
I gotta say, I'm really surprised how unreliable the firmware update process is on this device.  It's kinda depressing to have it be "this" bad...  If I had a warning for anyone reading this it's **DO NOT TRY TO UPDATE YOUR FIRMWARE REMOTELY** as it's highly likely you will need to physically power cycle the device at least once.

Update: Device will not come up after UZG update...    Blue and Red flashing light on top

Oh look, others experiencing same thing: https://www.reddit.com/r/ZigBee/comments/1pxor90/zigstar_uzg01_unknown_zigbee_fw_after_update/

Just blue light flashing on top, no LAN status..

The official firmware repo show 0.2.6 as latest yet device is showing v1 exists?  https://github.com/mercenaruss/uzg-firmware/tree/main/bin

Attempting to use ESPFlasher

````
Using '/dev/ttyUSB0' as serial port.
Connecting......................................
Unexpected error: ESP is not in flash boot mode. If your board has a flashing pin, try again while keeping it pressed.
````

I was able to reflash using https://xzg.xyzroe.cc/install/

EDIT: I gave up and gave the device away.

**Comment by epiphanyplx** [comment]
Quick question, seems firmware update went bad (maybe, not really sure), lose 2-3 packets out of every 15 or so and can't access web page - seems to be reboot looping. Just blue light flashing.

Is there anything I can do that will allow me to keep the Zigbee config? 
Wasn't sure if the reflash you are mentioning will wipe that part or not. 
Home Assistant isn't able to communicate so can't backup from there. 

Have 56 devices so would love to not have to recreate.

**Comment by JohnMcLear** [comment]
@epiphanyplx I had the same concern, I stuck in another zigbee coordinator device and zigbee2mqqt knew which device was what.  Backup first tho, just in case :)

**Comment by epiphanyplx** [comment]
> @epiphanyplx I had the same concern, I stuck in another zigbee coordinator device and zigbee2mqqt knew which device was what.  Backup first tho, just in case :)

Well, not sure what happened - was out of town for a day and wasn't able to resolve before I left. 
When I returned everything was working fine (running firmware 202409xx).
Maybe the firmware update took hours? Or it failed X times then reverted? 

Honestly no clue, but it's working now - and I took a backup!
