### ISSUE TITLE
UZG-01 v0.2.6 won't upgrade to GitHub version v1.0.0 via the github update process in the UI

### ISSUE THREAD

**Issue by kelvtech-co-uk** [mercenaruss/uzg-firmware#44]
On my UZG-01 I click the "Install latest from Github" button, "Github download starting..." shows above the progress bar but then nothing happens, ever.  I was about to try uploading the ESP32 binary via the file update button but thankfully saw [this](https://github.com/mercenaruss/uzg-firmware/issues/43) issue.  Please can you advise on the upgrade process I need to follow.

FWIW...I'm using a wired network with a statically assigned IP, have enabled webserver authentication, set a custom hostname and changed the timezone.

I could try a reset before the update process but happy to provide some logging/testing before that if it will help.

Thanks

**Comment by xyzroe** [comment]
@KillerKelvUK
1. Please try restarting your device and then attempt the "Install latest from GitHub" option again.
2. To perform a successful manual update, download the *.ota.bin file and select it in the file update dialog within the web UI.

**Comment by kelvtech-co-uk** [comment]
Thanks, 1 didn't work but 2 did.
